[build]
  command = "cd startuphunt && npm install && npm run build"
  publish = "startuphunt/dist"

# WWW Canonicalization
[[redirects]]
  from = "https://www.launchitsite.netlify.app/*"
  to = "https://launchitsite.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.launchit.site/*"
  to = "https://launchit.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "VITE_ENV,VITE_API_URL,VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY" 